# Generated by Django 4.2.15 on 2025-01-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gainz_center_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('equipment_description', models.TextField()),
                ('image_link', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
    ]
